name: Java CI with Gradle

on:
  push:
    branches: ["main"]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #JDK 17버전 설치
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # 실행 권한 부여
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      #빌드
      - name: Build and Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar
      #도커 허브 로그인
      - name: Login To DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      #이미지 빌드 및 업로드
      - name: Image Build and Release to DockerHub
        env:
          NAME: ${{secrets.DOCKERHUB_USERNAME}}
          REPO: ${{secrets.DOCKERHUB_REPOSITORY}}
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest
